sudo: false
language: rust
rust: 
  - nightly

branches:
  except:
    - notes
    - developers-guides

# Only while clippy is failing
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux

script:
  - cargo build --verbose
  - cargo run
