[package]
name = "example"
version = "0.1.0"
build = "build.rs"

[build-dependencies.lalrpop]
version = "0.15.2"

[dependencies.lalrpop-util]
version = "0.15.2"

[dependencies.regex]
version = "0.2.0"
